name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # added this and the tests passed after Heroku deployment 
      APP_URL: https://ptt-trending.herokuapp.com
      DATABASE_URL: postgresql://qqbjdftfomapyt:8edf6ccebf49940d554574508e6a7bdf3793e2b7d3ead39ff353c2fe8ad6ed4f@ec2-34-236-199-229.compute-1.amazonaws.com:5432/d9d64867psc2p8
      OPENAI_API_KEY: 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

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
