name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # added this and the tests passed after Heroku deployment 
      APP_URL: https://ptt-trending.herokuapp.com
      DB_URI: postgresql://ptt_trending_user:1234@localhost:5432/ptt_trending_db
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

